blacklist pf_driver for buster
ros-infrastructure/ros_buildfarm_config pull request #218
Opened 2022-05-10 15:16 UTC by ipa-hsd

[Jenkins job](https://build.ros.org/job/Nbin_dbv8_dBv8__pf_driver__debian_buster_arm64__binary/3/) failed since it could not find the key `libcurlpp-dev`:
```
Looking for the '.dsc' file of package 'ros-noetic-pf-driver' with version '1.2.0-1'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 297, in __getitem__
    rawpkg = self._cache[key]
KeyError: 'libcurlpp-dev'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 216, in <module>
    main()
  File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 92, in main
    apt_cache, debian_pkg_names)
  File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 175, in get_binary_package_versions
    pkg = apt_cache[debian_pkg_name]
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 299, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'libcurlpp-dev'"
Build step 'Execute shell' marked build as failure
```

 As seen [here](https://packages.debian.org/sid/libcurlpp-dev), it has not been released for `buster`. Hence the concerned package [pf_driver](https://github.com/PepperlFuchs/pf_lidar_ros_driver/tree/main/pf_driver) needs to be blacklisted for `buster`.

refer https://answers.ros.org/question/400344/buildfarm-fails-for-noetic-with-keyerror-libcurlpp-dev/ for details

2022-05-10 15:18 UTC, ipa-hsd commented
related PR: https://github.com/ros/rosdistro/pull/33130

2022-05-10 16:31 UTC, tfoote requested changes
apparently we don't enforce alphabetical order with the linters. could you move yours up? And while you're there could you make an additional commit to shift aruco up too? I'd do it parallel, but that will cause a merge conflict with you.

2022-05-10 16:44 UTC, ipa-hsd commented
done

2022-05-10 19:57 UTC, tfoote approved these changes
Thanks for the iteration, lgtm

2022-05-10 21:00 UTC, sloretz approved these changes

2022-05-10 21:00 UTC, merged

2022-05-11 07:02 UTC, ipa-hsd commented
why is it still building for buster? https://build.ros.org/job/Nbin_db_dB64__pf_driver__debian_buster_amd64__binary/3/console. It is a job from today morning